package proceso;

public enum TypeCambio {
    NUEVO_LISTO,
    LISTO_EJECUTANDO,
    EJECUTANDO_BLOQUEADO,
    EJECUTANDO_TERMINADO,
    EJECUTANDO_LISTO,
    BLOQUEADO_LISTO,
    BLOQUEADO_TERMINADO;
}
